In [1]:
# Importing necessary libraries
import pandas as pd

In [2]:
year = 2022

In [3]:
import pandas as pd

def combine_population_data(year):
    hhgq_df = pd.read_csv(f'{year}/synthetic_households_gq.csv')
    hh_df = pd.read_csv(f'{year}/synthetic_households.csv')
    pergq_df = pd.read_csv(f'{year}/synthetic_persons_gq.csv')
    per_df = pd.read_csv(f'{year}/synthetic_persons.csv')

    hhgq_df['household_id'] += len(hh_df)
    pergq_df['household_id'] += len(hh_df)

    hhfull_df = pd.concat([hh_df, hhgq_df]).drop(columns=['PUMA'])
    hhfull_df['HHADJINC'] = hhfull_df['HHADJINC'].apply(lambda x: max(x, 0))
    hhfull_df.update(hhfull_df[['HHT', 'HUPAC', "BLD", 'GQ_type']].fillna(0))

    perfull_df = pd.concat([per_df, pergq_df]).drop(columns=['PUMA'])
    perfull_df.update(perfull_df[['ESR', 'COW', 'WKHP', 'SCHG', 'MIL', 'SCHL', 'OCCP', 'WKW']].fillna(0))

    # Save combined data or return it
    hhfull_df.to_csv(f'../abm_output/{year}/combined_households.csv', index=False)
    perfull_df.to_csv(f'../abm_output/{year}/combined_persons.csv', index=False)

# Example usage:
combine_population_data('2022')

In [6]:
test_1 = pd.read_csv(r'C:\Users\cra\OneDrive - San Diego Association of Governments\Documents\GitHub\Population-Sim\abm_output\2022\combined_persons.csv')
test_1

,mgra,household_id,SPORDER,AGEP,SEX,ESR,COW,WKHP,SCHG,RAC1P,HISP,MIL,SCHL,OCCP,WKW,NAICS2,SOC2
0,57,1,1,56,1,1.0,1.0,40.0,0,1,9,2.0,21.0,9030.0,1.0,48,53
1,57,2,1,31,1,6.0,1.0,0.0,0,1,1,2.0,19.0,4720.0,0.0,44,41
2,57,2,2,30,2,6.0,0.0,0.0,0,1,1,4.0,18.0,0.0,0.0,0,0
3,57,2,3,7,2,0.0,0.0,0.0,0,1,1,0.0,5.0,0.0,0.0,0,0
4,57,2,4,4,1,0.0,0.0,0.0,0,1,1,0.0,1.0,0.0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3282577,24280,1276879,1,41,1,6.0,0.0,0.0,0,1,1,4.0,6.0,0.0,0.0,0,0
3282578,24280,1276880,1,28,1,6.0,1.0,40.0,0,1,2,4.0,11.0,6260.0,5.0,23,47
3282579,24280,1276881,1,76,1,6.0,0.0,0.0,0,1,1,3.0,19.0,0.0,0.0,0,0
3282580,24280,1276882,1,46,1,6.0,0.0,0.0,0,9,2,4.0,13.0,0.0,0.0,0,0
3282581,24280,1276883,1,23,2,1.0,1.0,40.0,0,1,1,4.0,13.0,4840.0,6.0,56,41

# Merging HH and GQ populations

## Reading syntheic data

In [3]:
hhgq_df = pd.read_csv(fr'{year}\synthetic_households_gq.csv')
hh_df = pd.read_csv(fr'{year}\synthetic_households.csv')

In [4]:
# reading GQ syn hh as it has Type
# pergq_fname = os.path.join(runFolder_GQ, 'synthetic_persons_gq.csv')
# per_fname = os.path.join(runFolder, 'synthetic_persons.csv')
pergq_df = pd.read_csv(fr'{year}\synthetic_persons_gq.csv')
per_df = pd.read_csv(fr'{year}\synthetic_persons.csv')

hhgq_df['household_id'] = len(hh_df) + hhgq_df['household_id']
pergq_df['household_id'] = len(hh_df) + pergq_df['household_id']

In [5]:
hhfull_df = pd.concat([hh_df, hhgq_df])
hhfull_df = hhfull_df[[item for item in hhfull_df.columns if item not in ['PUMA']]]

In [6]:
hhfull_df['HHADJINC'] = hhfull_df['HHADJINC'].apply(lambda x : x if x > 0 else 0)

In [7]:
perfull_df = pd.concat([per_df, pergq_df])
perfull_df = perfull_df[[item for item in perfull_df.columns if item not in ['PUMA']]]

# Fixing null values

In [8]:
#na cols
colsnahh = ['HHT', 'HUPAC', "BLD", 'GQ_type']
for col in colsnahh:
    hhfull_df[col] = hhfull_df[col].fillna(0)

In [9]:
#perfull_df[ESR,COW, WKHP, SCHG, MIL, SCHL, OCCP, WKW]
colsnaper = ['ESR', 'COW', 'WKHP', 'SCHG', 'MIL', 'SCHL', 'OCCP', 'WKW']
for col in colsnaper:
    perfull_df[col] = perfull_df[col].fillna(0)

## Writing out full populations
-- save this in the T drive for ABM run

In [10]:
# hhfull_df.to_csv(fr'T:\socioec\Current_Projects\SR15\S0\version7\abm_csv\synthetic_households_{year}_01.csv', index=False)
# perfull_df.to_csv(fr'T:\socioec\Current_Projects\SR15\S0\version7\abm_csv\synthetic_persons_{year}_01.csv', index=False)

In [11]:
hhfull_df

        household_id   mgra  NP   HHADJINC  HHT  WIF  HUPAC  VEH  BLD  GQ_type
0                  1     57   1  204630.00  4.0  NaN    4.0  2.0  2.0      0.0
1                  2     57   7  108561.60  1.0  1.0    3.0  4.0  2.0      0.0
2                  3     57   3  107700.00  2.0  1.0    4.0  3.0  2.0      0.0
3                  4     57   1  715128.00  4.0  NaN    4.0  1.0  2.0      0.0
4                  5     57   8   46849.50  1.0  3.0    3.0  2.0  7.0      0.0
...              ...    ...  ..        ...  ...  ...    ...  ...  ...      ...
116406       1276879  24280   1   11308.50  0.0  NaN    0.0  NaN  0.0      3.0
116407       1276880  24280   1   12924.00  0.0  NaN    0.0  NaN  0.0      3.0
116408       1276881  24280   1   16962.75  0.0  NaN    0.0  NaN  0.0      3.0
116409       1276882  24280   1       0.00  0.0  NaN    0.0  NaN  0.0      3.0
116410       1276883  24280   1    6462.00  0.0  NaN    0.0  NaN  0.0      3.0

[1276883 rows x 10 columns]

In [12]:
perfull_df

,mgra,household_id,SPORDER,AGEP,SEX,ESR,COW,WKHP,SCHG,RAC1P,HISP,MIL,SCHL,OCCP,WKW,NAICS2,SOC2
0,57,1,1,56,1,1.0,1.0,40.0,0,1,9,2.0,21.0,9030.0,1.0,48,53
1,57,2,1,31,1,6.0,1.0,0.0,0,1,1,2.0,19.0,4720.0,0.0,44,41
2,57,2,2,30,2,6.0,0.0,0.0,0,1,1,4.0,18.0,0.0,0.0,0,0
3,57,2,3,7,2,0.0,0.0,0.0,0,1,1,0.0,5.0,0.0,0.0,0,0
4,57,2,4,4,1,0.0,0.0,0.0,0,1,1,0.0,1.0,0.0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116406,24280,1276879,1,41,1,6.0,0.0,0.0,0,1,1,4.0,6.0,0.0,0.0,0,0
116407,24280,1276880,1,28,1,6.0,1.0,40.0,0,1,2,4.0,11.0,6260.0,5.0,23,47
116408,24280,1276881,1,76,1,6.0,0.0,0.0,0,1,1,3.0,19.0,0.0,0.0,0,0
116409,24280,1276882,1,46,1,6.0,0.0,0.0,0,9,2,4.0,13.0,0.0,0.0,0,0
116410,24280,1276883,1,23,2,1.0,1.0,40.0,0,1,1,4.0,13.0,4840.0,6.0,56,41